version: "2.1"
services:
  code-server:
    build:
      context: .
    image: code-server-test-candidats:latest
    container_name: code-server-test-candidats
    # command: git clone ssh://git@gitlab.mipih.net:32022/prodige/hors-carto/entretien.git --branch complet
    environment:
      - "PUID=35554"
      - "PGID=35554"
      - "TZ=Etc/UTC"
      - "PASSWORD=password" #optional
      - "HASHED_PASSWORD=" #optional
      - "SUDO_PASSWORD=password" #optional
      - "SUDO_PASSWORD_HASH=" #optional
      - "PROXY_DOMAIN=code-server.my.domain" #optional
      - "DEFAULT_WORKSPACE=/config/workspace" #optional
      - "http_proxy: http://bouzaggou.a:Rep.135tazor@proxy.mipih.local:3128"
      - "https_proxy: http://bouzaggou.a:Rep.135tazor@proxy.mipih.local:3128"
      - "no_proxy: dv02.mipih.net"
    volumes:
      - /home/install/test-candidats/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  